<script>
  import AOS from 'aos';
  AOS.init({
    duration: 1200,
  });
</script>

<div class="card" data-aos="zoom-in-up">
  <slot></slot>
</div>

<style>
  .card {
    padding: 20px;
    margin: 30px auto;
    background-color: #1E4348;
    border: solid 1px #245053;
    box-shadow: 0px, 2px, 4px, rgba(0, 0, 0, 1);
    border-radius: 15px;
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
  }

  /* ----------------------------------------------
  * Generated by Animista on 2021-1-20 16:18:33
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation slide-top
  * ----------------------------------------
  */
  @-webkit-keyframes slide-top {
    0% {
      -webkit-transform: translateY(0);
              transform: translateY(0);
    }
    100% {
      -webkit-transform: translateY(-100px);
              transform: translateY(-100px);
    }
  }
  @keyframes slide-top {
    0% {
      -webkit-transform: translateY(0);
              transform: translateY(0);
    }
    100% {
      -webkit-transform: translateY(-100px);
              transform: translateY(-100px);
    }
  }

</style>